services:
  db:
    image: postgres:15
    container_name: event_db
    restart: always
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    command: /start
    volumes:
      - .:/app
      - ./event_images:/app/event_images
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
