"""purpose field updated

Revision ID: 13e13bd8f972
Revises: d58a922481d7
Create Date: 2025-06-14 23:31:40.281461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13e13bd8f972'
down_revision: Union[str, None] = 'd58a922481d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('person_purpose_enum', postgresql.ENUM('att', 'info', name='person_purpose_enum'), nullable=True))
    op.drop_column('events', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('purpose', postgresql.ENUM('att', 'info', name='person_purpose_enum'), autoincrement=False, nullable=True))
    op.drop_column('events', 'person_purpose_enum')
    # ### end Alembic commands ###
