"""device id removed from heartbeat

Revision ID: 432bd4f36f3b
Revises: 8e095a8abd47
Create Date: 2025-06-17 16:45:09.634832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432bd4f36f3b'
down_revision: Union[str, None] = '8e095a8abd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_device_id'), table_name='heartbeats')
    op.drop_column('heartbeats', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heartbeats', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_heartbeats_device_id'), 'heartbeats', ['device_id'], unique=False)
    # ### end Alembic commands ###
