"""major event, minor event optional -> required

Revision ID: 57fc85862bac
Revises: e152061976fa
Create Date: 2025-06-14 17:43:18.168411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fc85862bac'
down_revision: Union[str, None] = 'e152061976fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'major_event',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'minor_event',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.alter_column('events', 'minor_event',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'major_event',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
