"""picture url field added

Revision ID: 8e095a8abd47
Revises: ecf0b67b93b7
Create Date: 2025-06-17 03:14:12.996549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import MetaData

# revision identifiers, used by Alembic.
revision: str = '8e095a8abd47'
down_revision: Union[str, None] = 'ecf0b67b93b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_post_count', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_state', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('major_event', sa.Integer(), nullable=False),
    sa.Column('minor_event', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=True),
    sa.Column('verify_no', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('person_name', sa.String(), nullable=True),
    sa.Column('purpose', postgresql.ENUM('att', 'info', name='person_purpose_enum', metadata=MetaData()), nullable=True),
    sa.Column('zone_type', sa.Integer(), nullable=True),
    sa.Column('swipe_card_type', sa.Integer(), nullable=True),
    sa.Column('card_no', sa.String(), nullable=True),
    sa.Column('card_type', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('current_verify_mode', sa.String(), nullable=True),
    sa.Column('current_event', sa.Boolean(), nullable=True),
    sa.Column('front_serial_no', sa.Integer(), nullable=True),
    sa.Column('attendance_status', sa.String(), nullable=True),
    sa.Column('pictures_number', sa.Integer(), nullable=True),
    sa.Column('mask', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_attendance_status'), 'events', ['attendance_status'], unique=False)
    op.create_index(op.f('ix_events_date_time'), 'events', ['date_time'], unique=False)
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_person_id'), 'events', ['person_id'], unique=False)
    op.create_index(op.f('ix_events_person_name'), 'events', ['person_name'], unique=False)
    op.create_index(op.f('ix_events_picture_url'), 'events', ['picture_url'], unique=False)
    op.create_table('heartbeats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_post_count', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_state', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_date_time'), 'heartbeats', ['date_time'], unique=False)
    op.create_index(op.f('ix_heartbeats_device_id'), 'heartbeats', ['device_id'], unique=False)
    op.create_index(op.f('ix_heartbeats_id'), 'heartbeats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_id'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_device_id'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_date_time'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_events_picture_url'), table_name='events')
    op.drop_index(op.f('ix_events_person_name'), table_name='events')
    op.drop_index(op.f('ix_events_person_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_index(op.f('ix_events_date_time'), table_name='events')
    op.drop_index(op.f('ix_events_attendance_status'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
