"""create events table

Revision ID: a7c6a1af28af
Revises: 
Create Date: 2025-06-11 01:23:33.358908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7c6a1af28af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_state', sa.String(), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('employee_no', sa.String(), nullable=True),
    sa.Column('major_event_type', sa.Integer(), nullable=False),
    sa.Column('sub_event_type', sa.Integer(), nullable=False),
    sa.Column('current_verify_mode', sa.String(), nullable=True),
    sa.Column('attendance_status', sa.String(), nullable=True),
    sa.Column('face_rect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
