"""small change to the database

Revision ID: e152061976fa
Revises: 961efc289316
Create Date: 2025-06-14 17:22:44.644663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e152061976fa'
down_revision: Union[str, None] = '961efc289316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('purpose', postgresql.ENUM('ATTENDANCE', 'INFORMATION', name='person_purpose_enum'), nullable=True))
    op.drop_column('events', 'person_purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('person_purpose', postgresql.ENUM('att', 'info', name='person_purpose_enum'), autoincrement=False, nullable=True))
    op.drop_column('events', 'purpose')
    # ### end Alembic commands ###
